cabal-version:      3.4
name:               gentoo-utils
version:            0.1.0.0
synopsis:
    An interface for running programs and utilities specific to Gentoo Linux

tested-with:        GHC == { 9.4.8, 9.6.7, 9.8.4, 9.10.2, 9.12.2 }

-- description:
homepage:
    https://github.com/gentoo-haskell/cabal-portage/tree/main/gentoo-utils
bug-reports:        https://github.com/gentoo-haskell/cabal-portage/issues

license:            AGPL-3.0-only
license-file:       LICENSE
author:             Gentoo Authors
maintainer:         hololeap@protonmail.com

copyright:          Copyright (C) 2025 Gentoo Authors
category:           System
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

source-repository head
    type:           git
    location:       https://github.com/gentoo-haskell/cabal-portage.git
    branch:         main
    subdir:         gentoo-utils

flag pedantic
    description: Enable -Werror
    default:     False
    manual:      True

common all
    ghc-options:        -Wall
    if flag(pedantic)
        ghc-options:    -Werror

common fast
    ghc-options:        -threaded
                        -with-rtsopts=-N

library
    import: all
    exposed-modules:
        , Distribution.Gentoo.Utils.Eix
        , Distribution.Gentoo.Utils.Emerge
        , Distribution.Gentoo.Utils.Exe
        , Distribution.Gentoo.Utils.Pquery
        , Distribution.Portage.Types.Orphans
    -- other-modules:
    other-extensions:
        , LambdaCase
    build-depends:
        , base >=4.13 && <4.22
        , parsable >=0.1 && <0.2
        , portage-hs >=0.1 && <0.2
        , bytestring >=0.11 && <0.13
        , conduit-run ^>= 0.1.0.0
        , directory <1.4
        , hashable ^>=1.4.7.0
        , mtl ^>=2.3.1
        , safe-exceptions ^>= 0.1.7.4
        , stm ^>=2.5.3.1
        , text <2.2
        , unordered-containers ^>= 0.2.20
        , validation-selective ^>= 0.2.0.0
    hs-source-dirs:   src
    default-language: GHC2021

test-suite gentoo-utils-test
    import: all, fast
    default-language: GHC2021
    -- other-modules:
    -- other-extensions:
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    build-depends:
        , gentoo-utils
        , base >=4.13 && <4.22
